### ISSUE TITLE
No textures transmitted

### ISSUE THREAD

**Issue by TheJackFace** [marek-simonik/record3d_unity_demo#5]
Hi, 

using release 1.3.0 in Unity 2020.3 on Windows 10 and v1.6.10 of Record3D on iPhone12 Pro, I get a "started streaming" log message in Unity and the app also says its streaming ("Connected, streaming RGBD"), however, the texture buffer stays empty/null.

(Also, the connection only starts if I have iTunes running in the background on my PC - not sure if this is intended or not.)

Any advice on how I can get the texture stream to work? Many thanks!

**Comment by marek-simonik** [comment]
Hi,

it seems like the demo does work on my computer; I am using Windows 10, Unity 2020.3.25f1 LTS, Windows 10 and Record3D v1.6.10 on an iPhone 13 Pro. Let me enumerate the exact steps I took:

0. Connect your iPhone to your computer via USB, open iTunes and verify that you pressed "*Trust this device*" on your iPhone (if the pop-up showed up). Also, please double-checked that iTunes can "see" your iPhone.
1. Download [the `record3d_unity_demo` release 1.3.0 from this link](https://github.com/marek-simonik/record3d_unity_demo/archive/refs/tags/v1.3.0.zip) and unzip it.
2. Copy [`record3d_unity_streaming.dll` from this link](https://github.com/marek-simonik/record3d_unity_streaming/releases/download/v1.3.0/record3d_unity_streaming.dll) to `C:\Windows\System32`.
3. Open Unity 2020.3.25f1 LTS, import the demo project and open it in Unity and wait for the demo to be fully loaded by Unity.
4. After the demo has been fully loaded, close all Unity windows. (The demo won't work the first time you import it and I am not sure why this happens.)
5. Open the demo in Unity again. This time, you should see colorful particles - see the first attached screenshot.
6. Force-kill / force-close Record3D and open it again on your iPhone, go to the Settings tab, enable USB streaming, switch back to the Record tab, tap the round red button and switch to the selfie camera (just for convenience).
7. Hit the "Play" button in Unity and after a few seconds, you should see the live stream - see the second attached photo.

Please let me know if it was possible to get the demo to work by following the exact steps mentioned above.

P.S. iTunes is need, because the iTunes services running in the background enable USB communication between Record3D and the computer. I think I didn't have to have an iTunes window opened for the demo to work, but after opening Windows Task Manager, I could see iTunes running in the background.

**This is how the demo should look like before you start streaming:**
![record3d-unity-demo-stopped](https://user-images.githubusercontent.com/53453633/148686688-2f771ad3-a783-4d03-9904-e71a021baf6f.png)

**This is how the demo should look like while streaming:**
![record3d-unity-demo-running](https://user-images.githubusercontent.com/53453633/148686696-082eebba-67f6-452f-9428-a4bd6ee15d46.png)

**Comment by TheJackFace** [comment]
Hi Marek, thank you very much for the detailled explantion! I followed the steps you outlined exactly and now everything is working as intended.
I now think my issue might have been an outdated version of the .dll in System32.
Again, many thanks!

**Comment by marek-simonik** [comment]
I'm glad to hear the demo works now, thanks for letting me know! I am therefore closing this issue.

If you would have any follow-up questions, just send me an email at support@record3d.app or add a new comment to this issue.
